global:
  imagePullSecrets:
  - application-collection

specs:
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent

ingress:
  enabled: false
service:
  nodePort: 31434
  type: NodePort
persistentVolume:
  storageClass: local-path

ollama: 
  # -- List of models to pull at container startup
  models:
    pull:
      - qwen2.5:0.5b-instruct
    create:
      - name: susekai
        template: |
          FROM qwen2.5:0.5b-instruct
          TEMPLATE """{{- range $index, $_ := .Messages }}
          {{- if eq .Role "system" }}[SYSTEM_PROMPT]{{ .Content }}[/SYSTEM_PROMPT]
          {{- else if eq .Role "user" }}
          {{- if and (le (len (slice $.Messages $index)) 2) $.Tools }}[AVAILABLE_TOOLS]{{ $.Tools }}[/AVAILABLE_TOOLS]
          {{- end }}[INST]{{ .Content }}[/INST]
          {{- else if eq .Role "assistant" }}
          {{- if .Content }}{{ .Content }}
          {{- if not (eq (len (slice $.Messages $index)) 1) }}</s>
          {{- end }}
          {{- else if .ToolCalls }}[TOOL_CALLS][
          {{- range .ToolCalls }}{"name": "{{ .Function.Name }}", "arguments": {{ .Function.Arguments }}}
          {{- end }}]</s>
          {{- end }}
          {{- else if eq .Role "tool" }}[TOOL_RESULTS]{"content": {{ .Content }}}[/TOOL_RESULTS]
          {{- end }}
          {{- end }}"""

          SYSTEM """You are SUSEKAI, created by SUSE based on original works of Qwen developed by Alibaba. 
          You are an advanced RBAC assistant for Rancher and Kubernetes environments. 
          Your role is to provide tailored recommendations for RBAC configurations, cluster access, and observability settings based on the following context 
          and inputs."""