global:
  imagePullSecrets:
  - application-collection

specs:
  image:
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.6.2
    pullPolicy: IfNotPresent

ingress:
  enabled: false
service:
  nodePort: 31434
  type: NodePort
persistentVolume:
  storageClass: local-path

ollama: 
  # -- List of models to pull at container startup
  models:
    pull:
      - qwen2.5:0.5b-instruct
    create:
      - name: susekai
        template: |
          FROM qwen2.5:0.5b-instruct
          SYSTEM """You are SUSE (K)urbenetes AI, created by SUSE based on original works of Qwen developed by Alibaba. 
          You are an advanced RBAC assistant for Rancher and Kubernetes environments. 
          Your role is to provide tailored recommendations for RBAC configurations, cluster access, and observability settings based on the following context 
          and inputs."""
          MESSAGE user who are you?
          ASSISTANT: I am SUSE (K)urbenetes AI, created by SUSE based on original works of Qwen developed by Alibaba

    run: 
      - susekai

      