apiVersion: apps/v1
kind: Deployment
metadata:
  name: suseai-operator
  namespace: suseai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suseai-op
  template:
    metadata:
      labels:
        app: suseai-op
    spec:
      containers:
        - name: suseai-op
          image: curlimages/curl:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          command: ["/bin/bash"]
          args:
            - "curl -X POST http://open-webui.suseai.svc.cluster.local:8000/api/v1/configs/tool_servers -H 'Authorization: Bearer sk-ec42c6cce14a42188653b03895831291' -H  'Content-Type: application/json' -d '{'TOOL_SERVER_CONNECTIONS':[{'url': 'http://mcpo-service.suseai.svc.suseai.cluster.local:8000/kubernetes','path': 'openai.json','auth_type': 'Authorization: Bearer','key': 'top-secret','config': {},'additionalProp1': {}}]}'"
