# This is an example overrides yaml enabling deployment of ollama, open-webui, milvus standalone with local storage. 
# Please update these overrides as needed for your environment.
# This is an example of services deployed in suse-private-ai namespace with suse-gen-ai release name.
global:
  imagePullSecrets:
  - application-collection
ollama:
  #To learn more about the entries, helm show values oci://dp.apps.rancher.io/charts/ollama
  enabled: true
  persistentVolume:
    enabled: true
    storageClass: local-path
open-webui:
  #To learn more about the entries, helm show values oci://dp.apps.rancher.io/charts/open-webui
  enabled: true
  ollamaUrls:
  - http://suse-ai-ollama.suseai.svc.cluster.local:11434
  persistence:
    enabled: true
    storageClass: local-path
  ollama:
    enabled: false
  ingress:
    host: suse-ollama-webui 
  extraEnvVars:
  - name: DEFAULT_MODELS
    value: "gemma:2b"
  - name: DEFAULT_USER_ROLE
    value: "user"
  - name: WEBUI_NAME
    value: "SUSE AI"
  - name: GLOBAL_LOG_LEVEL
    value: INFO
  - name: VECTOR_DB
    value: "milvus"
  - name: MILVUS_URI
    value: http://suse-ai-milvus.suseai.svc.cluster.local:19530
milvus:
  enabled: true
  cluster:
    enabled: false
  standalone:
    persistence:
      persistentVolumeClaim:
        storageClass: local-path
  etcd:
    replicaCount: 1
    persistence:
      storageClassName: local-path
  minio:
    mode: standalone
    rootUser: "admin"
    rootPassword: "adminminio"
    persistence:
      storageClass: local-path
      size: 5Gi
    resources:
      requests:
        memory: 1024Mi
  kafka:
    enabled: false
pytorch:
  enabled: false